# Generated by Django 5.1.7 on 2025-04-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_valid',
            new_name='is_verified',
        ),
    ]
