# Generated by Django 5.1.7 on 2025-05-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_colorsize_color_alter_colorsize_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
